/*
 * This source file was generated by the Gradle 'init' task
 */
package project.pbo;

import java.util.Scanner;

import project.pbo.domain.Pengguna;
import project.pbo.domain.Admin;
import project.pbo.domain.Staff;
import project.pbo.domain.Owner;
import project.pbo.service.AuthService;

public class App {
    public String getGreeting() {
        return "Hello World baru!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        Scanner input = new Scanner(System.in);
        AuthService authService = new AuthService();

        String username;
        String password;
        int percobaan = 0;

        do{
            System.out.println("Username: > ");
            username = input.nextLine();

            System.out.println("Password: > ");
            password = input.nextLine();

            Pengguna pengguna = authService.login(username, password);
            if (pengguna != null){
                System.out.println("[SUKSES] Login berhasil sebagai " + pengguna.getRole());
                break;
            } else {
                System.out.println("Login gagal! Input username dan password dengan benar!");
                System.out.println("Percobaan yang Anda miliki adalah: " + (3 - (percobaan + 1)));
                percobaan++;
            }
        } while (percobaan <= 3);
        input.close();
    }
}
